import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { deployArtifacts } from './scripts/deploy.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const deployOnSuccessfulWatchBuild = {
	name: 'deploy-on-successful-watch-build',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;

			try {
				const target = await deployArtifacts();
				console.info(`Deployed plugin to ${target}`);
			} catch (error) {
				return {
					errors: [
						{
							text:
								error instanceof Error
									? error.message
									: String(error),
						},
					],
				};
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: prod ? [] : [deployOnSuccessfulWatchBuild],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
